### ISSUE TITLE
border-radius is not work for Image

### ISSUE THREAD

**Issue by pinqy520** [jacobp100/cssta#10]
um.. i'm not sure it is a cssta's issue.

for some reason (https://github.com/facebook/react-native/pull/14148) Image component is not support corner-specific border radius like `borderTopRightRadius`. but cssta translates `border-radius` to four specific border radius, and it is not work for Image Component.

----

code: 

``` javascript
const ImageRadius = cssta(Image) `
  width: 100px;
  height: 100px;
  border-radius: 50px;
  overflow: hidden;
`;


export default () => (
    <ImageRadius
        style={{ borderRadius: 10 }}
        source={{ uri: 'http://img1.skqkw.cn:888/2014/11/17/10/3u1qorvdoud-126128.jpg' }}
        resizeMode="cover" />
);
```

![image](https://user-images.githubusercontent.com/5719833/27070805-0937078c-504d-11e7-9aef-ce65a44ecc56.png)

**Comment by jacobp100** [comment]
You are 100% correct in the cause! We "fixed" this in styled-components by disabling the border-radius shorthand. It actually works in android, and it looks like they're working on it for iOS, so I think I'll just wait and see!

I don't really have a great workaround in the meantime. Sorry!

**Comment by pinqy520** [comment]
ok, thanks for your great work~!
