### ISSUE TITLE
Break line in android

### ISSUE THREAD

**Issue by thangkho** [jacobp100/cssta#30]
In device android, border line is break. How I can fix it?

**Comment by jacobp100** [comment]
I’m not sure I’m following. Could you post an error message?

**Comment by thangkho** [comment]
I copy your class Custom button in here https://github.com/jacobp100/cssta/blob/master/examples/CsstaNativeDemo/demos/CustomButton.js
and run in my device Samsung SM G-532G Android 6.0.1 api23 and here is my result
https://ibb.co/ejQpt8

**Comment by jacobp100** [comment]
Try,

```js
import { StyleSheet } from 'react-native'

cssta(Animated.View)`
  ...
  border: ${StyleSheet.hairlineWidth}px solid var(--primary);
  ...
`

**Comment by thangkho** [comment]
`const ButtonContainer = cssta(Animated.View) `
  --primary: #e67e22;
  --foreground: var(--primary);
  --background: white;
  margin: 10px 50px;
  padding: 10px 15px;
  border-radius: 1000px;
  border: ${StyleSheet.hairlineWidth}px solid var(--primary);
  background-color: var(--background);
  transition: background-color 0.2s;
  &[@active] {
    --foreground: white;
    --background: var(--primary);
  }
`;`
same result

**Comment by jacobp100** [comment]
Glad you fixed it!
