### ISSUE TITLE
Type issue when using defaultProps

### ISSUE THREAD

**Issue by i-yusuf** [jacobp100/cssta#67]
In typescript cheatsheet used defaultProps like that :

```jsx
const defaultProps = {
  activeOpacity: 0.75,
};

interface Props {
  ...
}

const Button = (props: Props & typeof defaultProps) => {
  ...
}

Button.defaultProps = defaultProps
```

But when I use it with given types in #42 I encountering that error :

![Screen Shot 2021-05-30 at 18 17 10](https://user-images.githubusercontent.com/80166476/120109790-9b8c6000-c173-11eb-9209-ceb9533ced9a.png)

I tried to handle it but I couldn't.

**Comment by jacobp100** [comment]
I think the recommendation is not to use `defaultProps`. I know the react team want to move away from it. What are you trying to do?

**Comment by i-yusuf** [comment]
Yeah you are right. I decided to use alternative method and it's ok now. But thanks again.

**Comment by jacobp100** [comment]
Glad to hear!
